---
title: "Results"
format: 
  html:
    fig-format: pdf
    embed-resources: true
    self-contained-math: true
    keep-md: true
editor: visual
crossref:
  fig-title: '**Figure S**'
  fig-labels: arabic
  tbl-title: '**Table S**'
  tbl-labels: arabic
  title-delim: ":"

---

```{r}
#| echo: false
#| include: false
knitr::opts_chunk$set(fig.path="figures/", echo = FALSE)
```


## Results

Predictions and xAI

```{r}
#| label: fig-Fig_1
#| fig-cap: "Predictions and ALE of bio9"
#| fig-width: 8
#| fig-height: 4
#| warning: false
#| message: false
library(cito)
library(raster)
library(sp)
library(rsample)
library(latticeExtra)
library(sp)
library(ggplot2)
library(maptools)
library(gridExtra)
results = readRDS("results/model.RDS")
nn.fit = results$model
nn.fit$use_model_epoch = length(nn.fit$weights)
predictions = results$pred

habitat_plot = 
  spplot(predictions, colorkey = list(space = "left"), )

g1 = habitat_plot

#### xAI #####

Ale = ALE(nn.fit, variable = "bio8")
g2 = Ale$bio8 + theme_bw()+ ggtitle("") + xlab("Bioclim 8: Mean Temperature of Wettest Quarter") + ylab("Change in occurrence probability")

```

